// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-UZRrdxRYFCBIimnuKqEgscphopQbDDI',
    appId: '1:1065481004292:web:a58a44771289e2cea01c51',
    messagingSenderId: '1065481004292',
    projectId: 'notes-5a1b2',
    authDomain: 'notes-5a1b2.firebaseapp.com',
    storageBucket: 'notes-5a1b2.firebasestorage.app',
    measurementId: 'G-TFW0S3NNHJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZeGlWOC2ciLMZ2FqqCmOe-179h94NYTw',
    appId: '1:1065481004292:android:f5948b63f5f5e1a9a01c51',
    messagingSenderId: '1065481004292',
    projectId: 'notes-5a1b2',
    storageBucket: 'notes-5a1b2.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBNfoVozZiS3bFtawN2zskTEhC0scDh-k',
    appId: '1:1065481004292:ios:4a65103ad1a32ad8a01c51',
    messagingSenderId: '1065481004292',
    projectId: 'notes-5a1b2',
    storageBucket: 'notes-5a1b2.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotes',
  );
}
